### PR TITLE
Solved Issue 7

### PR DESCRIPTION
**Pull request by nykash**
Solved issue 7

### CODE REVIEW

**Comment by nykash** [comment]
@Mibblez

**Comment by Mibblez** [comment]
Everything looks good but there's some small things I'd like you to fix.

When you're grabbing info for the file name (the waveform_type, voltage, hz, and degrees variables) you're adding a space if a regex match is found. Replace the spaces with an underscore. There also needs to be check to make sure that the csv file that's being passed in as an argument exists. You can use os.path.exists() for that. 

As far as formatting goes, there's some trailing whitespace in lines 32, 40, 45, and 65. Just delete that. Also, delete the comments from lines 48-59. And one last thing, make sure there's two blank lines before each function.

**Comment by nykash** [comment]
@Mibblez sorry for the delay, I made the changes for the issue 7

**Comment by Mibblez** [comment]
Everything looks good :+1:

**Pull request merged**
